In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\faheem-pc\documents\downloads\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\faheem-pc\documents\downloads\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\faheem-pc\documents\downloads\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\faheem-pc\documents\downloads\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\faheem-pc\documents\downloads\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\faheem-pc\documents\downloads\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd

In [3]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [4]:
df = pd.read_csv('compensation data.csv')
df

,experience_coding,python_user,r_user,sql_user,most_used,compensation
0,6.1,True,False,True,Scikit-learn,124267
1,12.3,True,True,True,Scikit-learn,236889
2,2.2,True,False,False,NaN,74321
3,2.7,False,False,True,NaN,62593
4,1.2,True,False,False,Scikit-learn,36288
...,...,...,...,...,...,...
25968,1.9,True,False,True,Scikit-learn,15800
25969,1.4,True,False,False,PyTorch,62456
25970,0.0,False,False,False,NaN,923
25971,9.4,True,False,True,Scikit-learn,60609
25972,0.0,False,False,False,NaN,493

In [5]:
df.shape

(25973, 6)

In [6]:
df.shape[0]

25973

In [7]:
df.shape[1]

6

In [8]:
df.info

<bound method DataFrame.info of        experience_coding  python_user  r_user  sql_user     most_used  \
0                    6.1         True   False      True  Scikit-learn
1                   12.3         True    True      True  Scikit-learn
2                    2.2         True   False     False           NaN
3                    2.7        False   False      True           NaN
4                    1.2         True   False     False  Scikit-learn
...                  ...          ...     ...       ...           ...
25968                1.9         True   False      True  Scikit-learn
25969                1.4         True   False     False       PyTorch
25970                0.0        False   False     False           NaN
25971                9.4         True   False      True  Scikit-learn
25972                0.0        False   False     False           NaN

       compensation
0            124267
1            236889
2             74321
3             62593
4             36288
...             ...
25968         15800
25969         62456
25970           923
25971         60609
25972           493

[25973 rows x 6 columns]>

In [9]:
df.dtypes

experience_coding    float64
python_user             bool
r_user                  bool
sql_user                bool
most_used             object
compensation           int64
dtype: object

In [10]:
df.head

<bound method NDFrame.head of        experience_coding  python_user  r_user  sql_user     most_used  \
0                    6.1         True   False      True  Scikit-learn
1                   12.3         True    True      True  Scikit-learn
2                    2.2         True   False     False           NaN
3                    2.7        False   False      True           NaN
4                    1.2         True   False     False  Scikit-learn
...                  ...          ...     ...       ...           ...
25968                1.9         True   False      True  Scikit-learn
25969                1.4         True   False     False       PyTorch
25970                0.0        False   False     False           NaN
25971                9.4         True   False      True  Scikit-learn
25972                0.0        False   False     False           NaN

       compensation
0            124267
1            236889
2             74321
3             62593
4             36288
...             ...
25968         15800
25969         62456
25970           923
25971         60609
25972           493

[25973 rows x 6 columns]>

In [11]:
df.tail

<bound method NDFrame.tail of        experience_coding  python_user  r_user  sql_user     most_used  \
0                    6.1         True   False      True  Scikit-learn
1                   12.3         True    True      True  Scikit-learn
2                    2.2         True   False     False           NaN
3                    2.7        False   False      True           NaN
4                    1.2         True   False     False  Scikit-learn
...                  ...          ...     ...       ...           ...
25968                1.9         True   False      True  Scikit-learn
25969                1.4         True   False     False       PyTorch
25970                0.0        False   False     False           NaN
25971                9.4         True   False      True  Scikit-learn
25972                0.0        False   False     False           NaN

       compensation
0            124267
1            236889
2             74321
3             62593
4             36288
...             ...
25968         15800
25969         62456
25970           923
25971         60609
25972           493

[25973 rows x 6 columns]>

In [12]:
df.head(30)

,experience_coding,python_user,r_user,sql_user,most_used,compensation
0,6.10,True,False,True,Scikit-learn,124267
1,12.30,True,True,True,Scikit-learn,236889
2,2.20,True,False,False,NaN,74321
3,2.70,False,False,True,NaN,62593
4,1.20,True,False,False,Scikit-learn,36288
5,1.00,True,False,False,PyTorch,61302
6,1.80,False,False,False,NaN,68984
7,6.10,True,False,False,TensorFlow,18858
8,4.50,True,False,True,Scikit-learn,55418
9,1.10,True,False,True,TensorFlow,614
10,2.70,True,True,True,NaN,70564
11,0.93,True,True,False,Scikit-learn,55525
12,0.32,True,False,False,NaN,61005
13,9.90,True,False,True,Scikit-learn,2846
14,0.78,True,False,False,TensorFlow,21
15,13.50,True,False,False,Scikit-learn,14699
16,26.50,True,False,True,Scikit-learn,2110
17,1.50,True,False,True,Scikit-learn,620
18,3.40,True,False,True,PyTorch,73527
19,0.60,False,False,False,NaN,6992
20,0.95,True,False,False,NaN,22311
21,4.60,True,True,True,Scikit-learn,1377
22,2.80,False,True,False,NaN,69174
23,28.20,True,False,True,Scikit-learn,117636
24,1.40,True,True,True,TensorFlow,65937
25,4.80,True,False,False,Scikit-learn,27856
26,0.37,True,True,False,Scikit-learn,903
27,4.50,True,False,False,TensorFlow,50501
28,4.40,True,False,False,Scikit-learn,482
29,0.69,True,False,False,NaN,70407

In [13]:
df.loc[4]

experience_coding             1.2
python_user                  True
r_user                      False
sql_user                    False
most_used            Scikit-learn
compensation                36288
Name: 4, dtype: object

In [14]:
df.loc[5,'r_user']

False

In [15]:
df.iloc[30]

experience_coding      1.5
python_user           True
r_user               False
sql_user             False
most_used              NaN
compensation          8690
Name: 30, dtype: object

In [16]:
df.iloc[45,4]

'Keras'

In [17]:
df.loc[4:26]

,experience_coding,python_user,r_user,sql_user,most_used,compensation
4,1.20,True,False,False,Scikit-learn,36288
5,1.00,True,False,False,PyTorch,61302
6,1.80,False,False,False,NaN,68984
7,6.10,True,False,False,TensorFlow,18858
8,4.50,True,False,True,Scikit-learn,55418
9,1.10,True,False,True,TensorFlow,614
10,2.70,True,True,True,NaN,70564
11,0.93,True,True,False,Scikit-learn,55525
12,0.32,True,False,False,NaN,61005
13,9.90,True,False,True,Scikit-learn,2846
14,0.78,True,False,False,TensorFlow,21
15,13.50,True,False,False,Scikit-learn,14699
16,26.50,True,False,True,Scikit-learn,2110
17,1.50,True,False,True,Scikit-learn,620
18,3.40,True,False,True,PyTorch,73527
19,0.60,False,False,False,NaN,6992
20,0.95,True,False,False,NaN,22311
21,4.60,True,True,True,Scikit-learn,1377
22,2.80,False,True,False,NaN,69174
23,28.20,True,False,True,Scikit-learn,117636
24,1.40,True,True,True,TensorFlow,65937
25,4.80,True,False,False,Scikit-learn,27856
26,0.37,True,True,False,Scikit-learn,903

In [18]:
df.iloc[65:42,:3]

Empty DataFrame
Columns: [experience_coding, python_user, r_user]
Index: []

In [19]:
df.loc[45:50,:'most_used']

    experience_coding  python_user  r_user  sql_user     most_used
45               3.10         True   False     False         Keras
46               0.26         True   False      True  Scikit-learn
47               2.10         True    True     False  Scikit-learn
48               4.40         True   False      True         Keras
49               5.20         True    True     False  Scikit-learn
50               0.70         True    True      True    TensorFlow

In [20]:
df1 = pd.read_csv('compensation data.csv')
df1

,experience_coding,python_user,r_user,sql_user,most_used,compensation
0,6.1,True,False,True,Scikit-learn,124267
1,12.3,True,True,True,Scikit-learn,236889
2,2.2,True,False,False,NaN,74321
3,2.7,False,False,True,NaN,62593
4,1.2,True,False,False,Scikit-learn,36288
...,...,...,...,...,...,...
25968,1.9,True,False,True,Scikit-learn,15800
25969,1.4,True,False,False,PyTorch,62456
25970,0.0,False,False,False,NaN,923
25971,9.4,True,False,True,Scikit-learn,60609
25972,0.0,False,False,False,NaN,493

In [21]:
df.iloc[[6,31,79,999,7809]]

,experience_coding,python_user,r_user,sql_user,most_used,compensation
6,1.8,False,False,False,NaN,68984
31,9.6,True,True,True,NaN,114648
79,1.5,True,False,True,NaN,70796
999,4.9,True,False,False,NaN,71502
7809,29.8,True,True,True,Scikit-learn,21951

In [22]:
df['python_user']

0         True
1         True
2         True
3        False
4         True
         ...
25968     True
25969     True
25970    False
25971     True
25972    False
Name: python_user, Length: 25973, dtype: bool

In [23]:
df.drop('sql_user', axis =1,inplace = True)

In [24]:
df

       experience_coding  python_user  r_user     most_used  compensation
0                    6.1         True   False  Scikit-learn        124267
1                   12.3         True    True  Scikit-learn        236889
2                    2.2         True   False           NaN         74321
3                    2.7        False   False           NaN         62593
4                    1.2         True   False  Scikit-learn         36288
...                  ...          ...     ...           ...           ...
25968                1.9         True   False  Scikit-learn         15800
25969                1.4         True   False       PyTorch         62456
25970                0.0        False   False           NaN           923
25971                9.4         True   False  Scikit-learn         60609
25972                0.0        False   False           NaN           493

[25973 rows x 5 columns]

In [25]:
df.drop(25970,inplace=True)

In [26]:
df

       experience_coding  python_user  r_user     most_used  compensation
0                    6.1         True   False  Scikit-learn        124267
1                   12.3         True    True  Scikit-learn        236889
2                    2.2         True   False           NaN         74321
3                    2.7        False   False           NaN         62593
4                    1.2         True   False  Scikit-learn         36288
...                  ...          ...     ...           ...           ...
25967                6.1         True   False  Scikit-learn         80090
25968                1.9         True   False  Scikit-learn         15800
25969                1.4         True   False       PyTorch         62456
25971                9.4         True   False  Scikit-learn         60609
25972                0.0        False   False           NaN           493

[25972 rows x 5 columns]

In [27]:
df2 = pd.read_csv('compensation data.csv',header = None)

In [28]:
df2

,0,1,2,3,4,5
0,experience_coding,python_user,r_user,sql_user,most_used,compensation
1,6.1,TRUE,FALSE,TRUE,Scikit-learn,124267
2,12.3,TRUE,TRUE,TRUE,Scikit-learn,236889
3,2.2,TRUE,FALSE,FALSE,NaN,74321
4,2.7,FALSE,FALSE,TRUE,NaN,62593
...,...,...,...,...,...,...
25969,1.9,TRUE,FALSE,TRUE,Scikit-learn,15800
25970,1.4,TRUE,FALSE,FALSE,PyTorch,62456
25971,0,FALSE,FALSE,FALSE,NaN,923
25972,9.4,TRUE,FALSE,TRUE,Scikit-learn,60609
25973,0,FALSE,FALSE,FALSE,NaN,493

In [29]:
df['r_user'] == 'True'

0        False
1        False
2        False
3        False
4        False
         ...
25967    False
25968    False
25969    False
25971    False
25972    False
Name: r_user, Length: 25972, dtype: bool

In [30]:
df[df['r_user'] == 'True']

Empty DataFrame
Columns: [experience_coding, python_user, r_user, most_used, compensation]
Index: []

In [31]:
df[(df['python_user'] == True) & (df['most_used'] == 'Scikit-learn')]

       experience_coding  python_user  r_user     most_used  compensation
0                   6.10         True   False  Scikit-learn        124267
1                  12.30         True    True  Scikit-learn        236889
4                   1.20         True   False  Scikit-learn         36288
8                   4.50         True   False  Scikit-learn         55418
11                  0.93         True    True  Scikit-learn         55525
...                  ...          ...     ...           ...           ...
25952               1.40         True   False  Scikit-learn         17757
25966               1.90         True   False  Scikit-learn          3932
25967               6.10         True   False  Scikit-learn         80090
25968               1.90         True   False  Scikit-learn         15800
25971               9.40         True   False  Scikit-learn         60609

[7593 rows x 5 columns]

In [32]:
df['most_used'].unique()

array(['Scikit-learn', nan, 'PyTorch', 'TensorFlow', 'Keras'],
      dtype=object)

In [33]:
df[df['most_used'] == 'PyTorch']

       experience_coding  python_user  r_user most_used  compensation
5                    1.0         True   False   PyTorch         61302
18                   3.4         True   False   PyTorch         73527
81                   6.6         True   False   PyTorch         57861
89                  28.2         True   False   PyTorch        268191
96                   1.7         True   False   PyTorch         10284
...                  ...          ...     ...       ...           ...
25949                9.8         True    True   PyTorch         90950
25960               17.8         True   False   PyTorch         41513
25961                3.7         True   False   PyTorch         65027
25963               25.4         True   False   PyTorch        483648
25969                1.4         True   False   PyTorch         62456

[2445 rows x 5 columns]

In [34]:
df[(df['most_used'] == 'PyTorch') |(df['most_used'] == 'Scikit-learn')]

       experience_coding  python_user  r_user     most_used  compensation
0                    6.1         True   False  Scikit-learn        124267
1                   12.3         True    True  Scikit-learn        236889
4                    1.2         True   False  Scikit-learn         36288
5                    1.0         True   False       PyTorch         61302
8                    4.5         True   False  Scikit-learn         55418
...                  ...          ...     ...           ...           ...
25966                1.9         True   False  Scikit-learn          3932
25967                6.1         True   False  Scikit-learn         80090
25968                1.9         True   False  Scikit-learn         15800
25969                1.4         True   False       PyTorch         62456
25971                9.4         True   False  Scikit-learn         60609

[10379 rows x 5 columns]

In [35]:
df[(df['most_used'] == 'PyTorch') &~ (df['most_used'] == 'Scikit-learn')]

       experience_coding  python_user  r_user most_used  compensation
5                    1.0         True   False   PyTorch         61302
18                   3.4         True   False   PyTorch         73527
81                   6.6         True   False   PyTorch         57861
89                  28.2         True   False   PyTorch        268191
96                   1.7         True   False   PyTorch         10284
...                  ...          ...     ...       ...           ...
25949                9.8         True    True   PyTorch         90950
25960               17.8         True   False   PyTorch         41513
25961                3.7         True   False   PyTorch         65027
25963               25.4         True   False   PyTorch        483648
25969                1.4         True   False   PyTorch         62456

[2445 rows x 5 columns]

In [36]:
df.python_user

0         True
1         True
2         True
3        False
4         True
         ...
25967     True
25968     True
25969     True
25971     True
25972    False
Name: python_user, Length: 25972, dtype: bool

In [37]:
df[df.python_user]

       experience_coding  python_user  r_user     most_used  compensation
0                    6.1         True   False  Scikit-learn        124267
1                   12.3         True    True  Scikit-learn        236889
2                    2.2         True   False           NaN         74321
4                    1.2         True   False  Scikit-learn         36288
5                    1.0         True   False       PyTorch         61302
...                  ...          ...     ...           ...           ...
25966                1.9         True   False  Scikit-learn          3932
25967                6.1         True   False  Scikit-learn         80090
25968                1.9         True   False  Scikit-learn         15800
25969                1.4         True   False       PyTorch         62456
25971                9.4         True   False  Scikit-learn         60609

[21860 rows x 5 columns]